# Generated by Django 3.2.20 on 2023-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='../default_book_cover_p9xfbf', upload_to='images/'),
        ),
    ]
